### ISSUE TITLE
AttributeDefinitionFloat min = max

### ISSUE THREAD

**Issue by ClemTB** [julietkilo/CANBabel#12]
I think there is a typo in AttributeDefinitionFloat constructor:
public AttributeDefinitionFloat(String name, AttrTarget target, float min, float max)
	{
		super(name, target, AttrType.FLOAT);
		this.min = min;
		this.max = min;  // <------------------- Here
		def = 0;
	}

**Comment by julietkilo** [comment]
Thanks for reporting. The same error is in the AttributeDefinitionInt contructor. Will fix it in the next days.
Cheers
Jens

**Comment by julietkilo** [comment]
Fixed in commit faccd2a
