### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by Mathsoum** [julietkilo/CANBabel#8]
Hello.

I'm looking forward to use CANBabel as a library for a professional project.
I'd like some clarification on under what license this sotfware is available.
In fact, I can see on [license.txt](https://github.com/julietkilo/CANBabel/blob/master/license.txt "license.txt") that it's distributed under the terms of the [GNU GPLv3](http://www.gnu.org/licenses/gpl.txt "GNU GPLv3"). But, I've found that the description of your project in the [pom.xml](https://github.com/julietkilo/CANBabel/blob/master/pom.xml "pom.xml") that it's distributed under the terms of the GNU [LGPLv3](http://www.gnu.org/licenses/gpl.txt "GNU LGPLv3").
So you see me a bit confused. As I'd like to use it (as a library), I'd like to know which one of these license is applicable. And so, I write you this question.

I'm sorry by the way used to contact you but I didn't found another way and reporting an issue seemed the best way to reach you.

**Comment by julietkilo** [comment]
Hi.
he intended license for CANBabel is the GPLv3. I'll correct the POM (which is a copy-paste bug from the Kayak project where the result files are used.) Thank you very much for your feedback and best of luck for your project.
