### ISSUE TITLE
Problems parsing dbc file

### ISSUE THREAD

**Issue by Chrispone** [julietkilo/CANBabel#9]
Hi,
parsing a dbc file generated by 3rd Party tool leads to problems and signals are not parsed. After analysing I realized, that the 3rd party tool doesn't insert a whitespace before the 'SG_' keyword. Due to the fact that 'SG_' is member of the KEYWORDS array it messes up the whole message and the signals cannot be parsed.
I checked the dbc file with different other dbc converters and all of them where able to parse the file correctly, therefore I assume it is ok to not use a leading whitespace before 'SG_'.

I think there a two issues:
- 'SG_' should not be part of the KEYWORDS array (till now it wasn't a problem because the testfile containes 'SG_' with a leading whitespace and it is not recognized as a KEYWORD
- DbcReader.java line 539 `String[] lineArray = line.toString().split("\\s+SG_\\s+");` should be `String[] lineArray = line.toString().split("\\s*SG_\\s+");`

BR,
Chrispone

**Comment by julietkilo** [comment]
Hi Chrispone,
I've changed the readin-test at lines 48-52 to get the issue ( https://github.com/julietkilo/CANBabel/blob/master/src/test/resources/read_in_test.dbc ) and have fixed the bug.
Thanks
Jens
